// <auto-generated />
using System;
using Estacionamento4.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Estacionamento4.Migrations
{
    [DbContext(typeof(EstacionamentoContext))]
    [Migration("20200925180358_camelcase")]
    partial class camelcase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Estacionamento4.Entities.Patio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DataFim");

                    b.Property<DateTime>("DataInicio");

                    b.Property<double?>("Tempo");

                    b.Property<float?>("Valor");

                    b.Property<string>("VeiculoPlaca");

                    b.HasKey("Id");

                    b.HasIndex("VeiculoPlaca");

                    b.ToTable("Patios");
                });

            modelBuilder.Entity("Estacionamento4.Entities.Veiculo", b =>
                {
                    b.Property<string>("Placa")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cor");

                    b.Property<string>("Marca");

                    b.Property<string>("Modelo");

                    b.HasKey("Placa");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("Estacionamento4.Entities.Patio", b =>
                {
                    b.HasOne("Estacionamento4.Entities.Veiculo", "Veiculo")
                        .WithMany("Patio")
                        .HasForeignKey("VeiculoPlaca");
                });
#pragma warning restore 612, 618
        }
    }
}
